### ISSUE TITLE
critical errors can get the frontend stuck, now

### ISSUE THREAD

**Issue by Cyberfly100** [timetag/ETA#94] opened 2019-09-17 16:31 UTC
A strange file caused the backend to have overflow errors, which caused the frontend to be stuck in the "working" animation. 
![image](https://user-images.githubusercontent.com/28017534/65061033-57463580-d979-11e9-8e81-2897c6c50dc2.png)

**Comment by linzuzeng** [comment] 2019-09-19 04:28
@Cyberfly100  Could you help me testing if it is fixed or not? You can try manually closing the back-end during an analysis.

**Comment by Cyberfly100** [comment] 2019-10-15 09:53
If I close the backend during analysis the frontend is still in the "ETA Running..." state and does not recover.
![image](https://user-images.githubusercontent.com/28017534/66821150-39e99480-ef42-11e9-8b18-819c552384bc.png)

**Comment by linzuzeng** [comment] 2019-10-15 18:20
Strange that the [Web GUI ](https://timetag.github.io/ETA/gui/src/renderer/) shows an error message and the close button when Backend crashed. Could be a Electron bug. I will try to update Electron the latest version.

**Comment by linzuzeng** [comment] 2019-10-15 18:27
Confirmed. The error message shows up after updating the Electron from 4.0 to 6.0. 
However, the message shows up multiple times, since ETA Frontend has a tiemer to constantly check the connection to the Backend.

**Comment by Cyberfly100** [comment] 2019-10-18 17:39
I have not investigated further, but closing the progress popup on the frontend can cause the backend to get stuck, in the newest unreleased version, it seems. Could this be related to recent changes or was it just unlucky timing?

**Comment by linzuzeng** [comment] 2019-10-18 17:53
I am trying to reproduce it but haven't seen it happening yet.
Were you using realtime recipe?

**Comment by linzuzeng** [comment] 2019-10-18 17:55
Also if the backend is running, the frontend doesn't show a button for close. It will show the close button only when the backend finishes the processing.

**Comment by Cyberfly100** [comment] 2019-10-18 19:20
true.. I have no idea how it was possible. It was with the new realtime recipe, but I cannot reproduce it.

**Comment by linzuzeng** [comment] 2019-12-09 21:19
close for now. Reopen when it happens again

**Closed as completed by linzuzeng** 2019-12-09 21:19 UTC
Labels: bug
